"""initial schema

Revision ID: d68db143309f
Revises: 
Create Date: 2026-08-19 16:42:26.396926

"""
from alembic import op
import sqlalchemy as sa
import ashare_review.db.types  # noqa: F401  (custom types)


revision = 'd68db143309f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', name='uq_companies_symbol_market')
    )
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.create_index('ix_dqi_status', ['status'], unique=False)
        batch_op.create_index('ix_dqi_symbol_trade_date', ['symbol', 'trade_date'], unique=False)
        batch_op.create_index('ix_dqi_type', ['issue_type'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('event_time', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_symbol_time', ['symbol', 'event_time'], unique=False)
        batch_op.create_index('ix_events_type', ['event_type'], unique=False)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('security_type', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price_tick', ashare_review.db.types.ExactDecimal(precision=18, scale=6), nullable=False),
    sa.Column('trade_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', name='uq_instruments_symbol_market')
    )
    op.create_table('market_data_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quote_time', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('price_type', sa.String(length=16), nullable=False),
    sa.Column('adjustment', sa.String(length=8), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', ashare_review.db.types.ExactDecimal(precision=18, scale=6), nullable=True),
    sa.Column('quality_status', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', 'trade_date', 'quote_time', 'source', 'price_type', 'adjustment', 'is_delayed', name='uq_mdp_dedup')
    )
    with op.batch_alter_table('market_data_points', schema=None) as batch_op:
        batch_op.create_index('ix_mdp_quality', ['quality_status'], unique=False)
        batch_op.create_index('ix_mdp_source_fetched', ['source', 'fetched_at'], unique=False)
        batch_op.create_index('ix_mdp_symbol_trade_date', ['symbol', 'market', 'trade_date'], unique=False)
        batch_op.create_index('ix_mdp_trade_date_type', ['trade_date', 'price_type'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('quantity', ashare_review.db.types.ExactDecimal(precision=18, scale=4), nullable=False),
    sa.Column('cost_price', ashare_review.db.types.ExactDecimal(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('created_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', name='uq_positions_symbol_market')
    )
    op.create_table('source_fetch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_fetch_runs', schema=None) as batch_op:
        batch_op.create_index('ix_sfr_source_started', ['source', 'started_at'], unique=False)
        batch_op.create_index('ix_sfr_status', ['status'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', ashare_review.db.types.ExactDecimal(precision=18, scale=4), nullable=False),
    sa.Column('price', ashare_review.db.types.ExactDecimal(precision=18, scale=6), nullable=False),
    sa.Column('fee', ashare_review.db.types.ExactDecimal(precision=18, scale=6), nullable=False),
    sa.Column('amount', ashare_review.db.types.ExactDecimal(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('settlement_rule', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('created_at', ashare_review.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_symbol_trade_date', ['symbol', 'trade_date'], unique=False)

    op.create_table('instrument_trade_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('trade_cycle', sa.String(length=4), nullable=False),
    sa.Column('min_trade_unit', ashare_review.db.types.ExactDecimal(precision=18, scale=4), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('settlement_rule', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', name='uq_trade_rules_symbol_market')
    )
    with op.batch_alter_table('instrument_trade_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrument_trade_rules_instrument_id'), ['instrument_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_trade_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrument_trade_rules_instrument_id'))

    op.drop_table('instrument_trade_rules')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_symbol_trade_date')

    op.drop_table('trades')
    with op.batch_alter_table('source_fetch_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_sfr_status')
        batch_op.drop_index('ix_sfr_source_started')

    op.drop_table('source_fetch_runs')
    op.drop_table('positions')
    with op.batch_alter_table('market_data_points', schema=None) as batch_op:
        batch_op.drop_index('ix_mdp_trade_date_type')
        batch_op.drop_index('ix_mdp_symbol_trade_date')
        batch_op.drop_index('ix_mdp_source_fetched')
        batch_op.drop_index('ix_mdp_quality')

    op.drop_table('market_data_points')
    op.drop_table('instruments')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_type')
        batch_op.drop_index('ix_events_symbol_time')

    op.drop_table('events')
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.drop_index('ix_dqi_type')
        batch_op.drop_index('ix_dqi_symbol_trade_date')
        batch_op.drop_index('ix_dqi_status')

    op.drop_table('data_quality_issues')
    op.drop_table('companies')
    # ### end Alembic commands ###
